services:
  postgres:
    image: 'postgres:latest'
    container_name: benchmark-js-pg
    restart: always
    # command: postgres -c 'max_connections=450'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: midapa
      POSTGRES_DB: postgres_database
    ports:
      - 5432:5432
    volumes:
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    # command: [postgres, -c, config_file=/etc/postgresql/postgresql.conf]
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:latest'
    container_name: benchmark-js-redis
    ports:
      - '6379:6379'
    volumes:
      - 'benchmark-js-redis_data:/data'

  # redis:
  #   image: docker.dragonflydb.io/dragonflydb/dragonfly
  #   ports:
  #     - "6379:6379"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4g
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: benchmark-js-redis-commander
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - redis

volumes:
  benchmark-js-redis_data:
    external: false
